ac_backup: update remote prune to include db backups

diff --git a/roles/ac_backup/templates/acsm_backup.sh.j2 b/roles/ac_backup/templates/acsm_backup.sh.j2
--- a/roles/ac_backup/templates/acsm_backup.sh.j2
+++ b/roles/ac_backup/templates/acsm_backup.sh.j2
@@ -77,6 +77,15 @@ if [ $? != 0 ]; then
     exit 1;
 fi
 
+ssh -i /home/{{ app_user }}/.ssh/{{ app_user }} \
+    {{ ac_user }}@{{ ac_fqdn }} "find {{ ac_backup_source }} \
+        -name *.gz -ctime +1 -exec rm -rvf '{}' \;"
+
+if [ $? != 0 ]; then
+    echo "$(date +%Y%m%d:%H%M%S): prune failed. Exiting"
+    exit 1;
+fi
+
 # exit
 echo "$(date +%Y%m%d:%H%M%S): Done. Time taken: $SECONDS seconds.";
 times;
