ac_backup: update local file cleanup to include .gz files

diff --git a/roles/ac_backup/templates/acsm_backup.sh.j2 b/roles/ac_backup/templates/acsm_backup.sh.j2
--- a/roles/ac_backup/templates/acsm_backup.sh.j2
+++ b/roles/ac_backup/templates/acsm_backup.sh.j2
@@ -51,6 +51,14 @@ if [ $? != 0 ]; then
     exit 1;
 fi
 
+# prune local files
+echo "Removing local .gz older than 30 (+29) days old."
+find {{ ac_backup_destination }} -name *.gz -ctime +29 -exec rm -rvf '{}' \;
+if [ $? != 0 ]; then
+    echo "$(date +%Y%m%d:%H%M%S): local prune failed. Exiting"
+    exit 1;
+fi
+
 # copy remote files
 echo "Pulling backups from {{ ac_fqdn }}";
 
